/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./node_modules/flowbite/**/*.js",
    ],
    theme: {
        extend: {
            fontFamily: {
                text: ["Geist", "sans-serif"],
            },
            colors: {
                background: "hsl(0, 0%, 100%)",
                foreground: "hsl(240, 10%, 3.9%)",
                card: "hsl(0, 0%, 100%)",
                "card-foreground": "hsl(240, 10%, 3.9%)",
                popover: "hsl(0, 0%, 100%)",
                "popover-foreground": "hsl(240, 10%, 3.9%)",
                primary: "hsl(240, 5.9%, 10%)",
                "primary-foreground": "hsl(0, 0%, 98%)",
                secondary: "hsl(240, 4.8%, 95.9%)",
                "secondary-foreground": "hsl(240, 5.9%, 10%)",
                muted: "hsl(240, 4.8%, 95.9%)",
                "muted-foreground": "hsl(240, 3.8%, 46.1%)",
                accent: "hsl(240, 4.8%, 95.9%)",
                "accent-foreground": "hsl(240, 5.9%, 10%)",
                destructive: "hsl(0, 72.22%, 50.59%)",
                "destructive-foreground": "hsl(0, 0%, 98%)",
                border: "hsl(240, 5.9%, 90%)",
                input: "hsl(240, 5.9%, 90%)",
                ring: "hsl(240, 5%, 64.9%)",
                "chart-1": "hsl(12, 76%, 61%)",
                "chart-2": "hsl(173, 58%, 39%)",
                "chart-3": "hsl(197, 37%, 24%)",
                "chart-4": "hsl(43, 74%, 66%)",
                "chart-5": "hsl(27, 87%, 67%)",
                "sidebar-background": "hsl(0, 0%, 98%)",
                "sidebar-foreground": "hsl(240, 5.3%, 26.1%)",
                "sidebar-primary": "hsl(240, 5.9%, 10%)",
                "sidebar-primary-foreground": "hsl(0, 0%, 98%)",
                "sidebar-accent": "hsl(240, 4.8%, 95.9%);",
                "sidebar-accent": "hsl(240, 4.8%, 95.9%)",
                "sidebar-accent-foreground": "hsl(240, 5.9%, 10%)",
                "sidebar-border": "hsl(220, 13%, 91%)",
                "sidebar-ring": "hsl(240, 5%, 64.9%)",
                "red-primary": "hsl(0, 72.2%, 50.6%)",
                "red-primary-foreground": "hsl(0, 85.7%, 97.3%)",
                "red-secondary": "hsl(0, 0%, 96.1%)",
                "red-secondary-foreground": "hsl(0, 0%, 9%)",
            },
            borderRadius: {
                DEFAULT: "0.5rem",
            },
        },
    },
    plugins: [require("flowbite/plugin")],
};
